/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.lms.view;

import edu.lms.controller.RegisterController;
import edu.lms.dto.RegisterDto;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class RegisterView extends javax.swing.JFrame {
    private RegisterController registerController;
    private final Random random= new Random();
        private Set <String> idSet = new HashSet<>();
    /**
     * Creates new form RegisterView
     */
    public RegisterView() {
       
        super("Register Form");
         
        registerController = new RegisterController();
             
        initComponents();
        GeneratingMemberId();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblUserId = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblAnswer = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtAnswer = new javax.swing.JTextField();
        txtUserId = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblRole = new javax.swing.JLabel();
        lblSecQ = new javax.swing.JLabel();
        SecQCombo = new javax.swing.JComboBox<>();
        roleCombo = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 51), 2), "Register Form", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(0, 102, 204))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        lblUserId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUserId.setForeground(new java.awt.Color(51, 51, 51));
        lblUserId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserId.setText("User Id :");
        lblUserId.setToolTipText("");
        jPanel1.add(lblUserId);
        lblUserId.setBounds(50, 60, 134, 26);

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(51, 51, 51));
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setText("Password  :");
        lblPassword.setToolTipText("");
        jPanel1.add(lblPassword);
        lblPassword.setBounds(50, 150, 134, 26);

        lblAnswer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAnswer.setForeground(new java.awt.Color(51, 51, 51));
        lblAnswer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAnswer.setText("Answer :");
        lblAnswer.setToolTipText("");
        jPanel1.add(lblAnswer);
        lblAnswer.setBounds(50, 310, 140, 26);

        lblEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(51, 51, 51));
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("Email :");
        lblEmail.setToolTipText("");
        jPanel1.add(lblEmail);
        lblEmail.setBounds(50, 190, 134, 26);

        lblUserName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(51, 51, 51));
        lblUserName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUserName.setText("User Name :");
        lblUserName.setToolTipText("");
        jPanel1.add(lblUserName);
        lblUserName.setBounds(50, 110, 134, 26);

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(340, 380, 90, 25);

        txtAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnswerActionPerformed(evt);
            }
        });
        jPanel1.add(txtAnswer);
        txtAnswer.setBounds(230, 310, 120, 22);
        jPanel1.add(txtUserId);
        txtUserId.setBounds(230, 60, 90, 22);
        jPanel1.add(txtUserName);
        txtUserName.setBounds(230, 110, 90, 22);

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmail);
        txtEmail.setBounds(230, 190, 90, 22);

        txtPassword.setText("jPasswordField1");
        jPanel1.add(txtPassword);
        txtPassword.setBounds(230, 150, 82, 22);

        lblRole.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRole.setForeground(new java.awt.Color(51, 51, 51));
        lblRole.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRole.setText("Role :");
        lblRole.setToolTipText("");
        jPanel1.add(lblRole);
        lblRole.setBounds(60, 230, 120, 26);

        lblSecQ.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSecQ.setForeground(new java.awt.Color(51, 51, 51));
        lblSecQ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSecQ.setText("Sequirity question :");
        lblSecQ.setToolTipText("");
        jPanel1.add(lblSecQ);
        lblSecQ.setBounds(40, 270, 140, 26);

        SecQCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your favourite colour", "Which is your first pet", "What was your favourite subject in school", "What was your dream job as a child" }));
        SecQCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecQComboActionPerformed(evt);
            }
        });
        jPanel1.add(SecQCombo);
        SecQCombo.setBounds(220, 270, 270, 24);

        roleCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Member", "Staff" }));
        roleCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleComboActionPerformed(evt);
            }
        });
        jPanel1.add(roleCombo);
        roleCombo.setBounds(230, 230, 90, 24);

        jButton3.setText("Go to login");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(460, 380, 100, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        registerUser();
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void SecQComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecQComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SecQComboActionPerformed

    private void roleComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleComboActionPerformed

    private void txtAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnswerActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
         new LoginView().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> SecQCombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAnswer;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblSecQ;
    private javax.swing.JLabel lblUserId;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JComboBox<String> roleCombo;
    private javax.swing.JTextField txtAnswer;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void registerUser(){
        try{
        RegisterDto dto = new RegisterDto(txtUserId.getText(),txtUserName.getText(),txtPassword.getText(),
        txtEmail.getText(),(String)roleCombo.getSelectedItem(),(String)SecQCombo.getSelectedItem(),txtAnswer.getText() );
        
        String resp= registerController.registerUser(dto);
        JOptionPane.showMessageDialog(this, resp);
        clearForm();
                
        }catch(Exception e){
            
         clearForm();
         e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error saving the user");
        }        
    }
     private void clearForm(){
         txtUserId.setText("");
         txtUserName.setText("");
         txtPassword.setText("");
         txtEmail.setText("");
         roleCombo.setToolTipText("");
         SecQCombo.setToolTipText("");
         txtAnswer.setText("");       
                
     }
    
    private void GeneratingMemberId(){       
        String uniqueId;
        do{
            uniqueId =String.valueOf(random.nextInt(1000)+1);
        }while(idSet.contains(uniqueId));
        
        idSet.add(uniqueId);
        txtUserId.setText(uniqueId);
  
    }  
}
