/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.lms.view;

import edu.lms.controller.BookController;
import edu.lms.controller.BorrowController;
import edu.lms.dto.BorrowDetailDto;
import edu.lms.dto.BorrowDto;
import edu.lms.entity.BorrowDetailEntity;
import edu.lms.entity.BorrowDetailsWrapper;
import edu.lms.entity.BorrowEntity;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class ReturnView extends javax.swing.JFrame {
     private BorrowController borrowController;
    private BookController bookController;
    private ArrayList <BorrowDetailDto> borrowDetailDtos;
    private ArrayList <BorrowDto> borrowDtos;
    /**
     * Creates new form ReturnView
     */
    public ReturnView() {
        borrowController = new BorrowController();
        bookController = new BookController();
        borrowDetailDtos= new ArrayList<>();
        borrowDtos = new  ArrayList<>();
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBorrowId = new javax.swing.JLabel();
        lblMemberId = new javax.swing.JLabel();
        lblRetunDate = new javax.swing.JLabel();
        txtBorrowId = new javax.swing.JTextField();
        txtMemberId = new javax.swing.JTextField();
        jdcReturnDate = new com.toedter.calendar.JDateChooser();
        lblFines = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnReturnBook = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnSearchDetail = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetail = new javax.swing.JTable();
        lblBookId = new javax.swing.JLabel();
        txtBookQty = new javax.swing.JTextField();
        btnSearchDetail1 = new javax.swing.JButton();
        txtFines = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        lblBookQty = new javax.swing.JLabel();
        txtBookId = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 153), 3, true), "Return Book Transaction", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 24), new java.awt.Color(0, 102, 204))); // NOI18N

        lblBorrowId.setText("Borrow Id");

        lblMemberId.setText("Member Id");

        lblRetunDate.setText("Return Date");

        lblFines.setText("Fines");

        btnReturnBook.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnReturnBook.setForeground(new java.awt.Color(204, 0, 204));
        btnReturnBook.setText("Return Book");
        btnReturnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnBookActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 204));
        jButton1.setText("Back");

        btnSearchDetail.setText("Search this member's details");
        btnSearchDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDetailActionPerformed(evt);
            }
        });

        tblDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetailMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDetail);

        lblBookId.setText("Book Id");

        btnSearchDetail1.setText("Search Total");
        btnSearchDetail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchDetail1ActionPerformed(evt);
            }
        });

        lblTotal.setText("Total Amount");

        lblBookQty.setText("Qty");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReturnBook)
                        .addGap(44, 44, 44)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBorrowId, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFines, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBookId, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRetunDate, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBookQty, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jdcReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFines, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtMemberId, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtBorrowId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(btnSearchDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(btnSearchDetail1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 417, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBookId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBookQty, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                        .addGap(656, 656, 656))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBorrowId)
                    .addComponent(txtBorrowId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchDetail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMemberId)
                    .addComponent(txtMemberId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBookId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBookQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBookQty, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFines, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFines, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jdcReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRetunDate))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchDetail1)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReturnBook)
                    .addComponent(jButton1))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetailMouseClicked
        // TODO add your handling code here:
        searchBorrowing();
    }//GEN-LAST:event_tblDetailMouseClicked

    private void btnSearchDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDetailActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_btnSearchDetailActionPerformed

    private void btnSearchDetail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchDetail1ActionPerformed
        // TODO add your handling code here:
        totalAmountSearch();
    }//GEN-LAST:event_btnSearchDetail1ActionPerformed

    private void btnReturnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnBookActionPerformed
        // TODO add your handling code here:
        returnBook();
    }//GEN-LAST:event_btnReturnBookActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReturnBook;
    private javax.swing.JButton btnSearchDetail;
    private javax.swing.JButton btnSearchDetail1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jdcReturnDate;
    private javax.swing.JLabel lblBookId;
    private javax.swing.JLabel lblBookQty;
    private javax.swing.JLabel lblBorrowId;
    private javax.swing.JLabel lblFines;
    private javax.swing.JLabel lblMemberId;
    private javax.swing.JLabel lblRetunDate;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblDetail;
    private javax.swing.JTextField txtBookId;
    private javax.swing.JTextField txtBookQty;
    private javax.swing.JTextField txtBorrowId;
    private javax.swing.JTextField txtFines;
    private javax.swing.JTextField txtMemberId;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void nextClearForm(){
        txtBookQty.setText("");
        txtBorrowId.setText("");
        txtFines.setText("");
        //lblBookData.setText("");
        txtBorrowId.setText("");
        txtMemberId.setText("");
        //jdcIssuedDate.setDateFormatString("");
        jdcReturnDate.setDateFormatString("");
        
    }
     private void loadTable(){
        String columns[]= {"BorrowId","Book Id","Member Id","Count","Due Date","Fines"};
        DefaultTableModel dtm = new DefaultTableModel(columns,0){
            public boolean isCellEditable(int row,int column){
                return false;
        }
     };
         tblDetail.setModel(dtm);
}
     
    private void loadData(){
        try{
            String borrowId= txtBorrowId.getText();
            BorrowDetailsWrapper wrapper = borrowController.getBorrowDetails(borrowId);
            BorrowEntity borrowEntity = wrapper.getBorrowEntity();
            ArrayList<BorrowDetailEntity> details = wrapper.getDetails();

             for (BorrowDetailEntity detail : details) {
                 if(detail.getReturnDate() == null){
                    Object data[]={detail.getBorrowId(),detail.getBookId(), borrowEntity.getMemberId(),detail.getQty(),borrowEntity.getDueDate(), detail.getFines()};
        
                   DefaultTableModel dtm= ( DefaultTableModel)tblDetail.getModel();
                dtm.addRow(data);
            }
                 }
              
}catch(Exception e){
    e.printStackTrace();
}
}
     private void searchBorrowing(){
            String memberId = tblDetail.getValueAt(tblDetail.getSelectedRow(),2).toString();
            String bookId = tblDetail.getValueAt(tblDetail.getSelectedRow(),1).toString();
            String fines = tblDetail.getValueAt(tblDetail.getSelectedRow(),5).toString();
            String qty = tblDetail.getValueAt(tblDetail.getSelectedRow(),3).toString();
            
            
            txtMemberId.setText(memberId);
            txtBookId.setText(bookId);
            txtBookQty.setText(qty);
            txtFines.setText(fines);
            }
     
    private void totalAmountSearch(){
        DefaultTableModel dtm= ( DefaultTableModel)tblDetail.getModel();
         // Get the row count from the table model
        int rowCount = dtm.getRowCount();
         
        
        double total= 0.0;
        //looping until rowcount
        for(int i = 0; i < rowCount; i++){
            String fineValue = dtm.getValueAt(i, 5).toString(); //getting the fineAmount from the column
            double fines = Double.parseDouble(fineValue);
            total+=fines;
        }
        txtTotal.setText(String.valueOf(total));
    }
           
    private void returnBook(){
        try{
           Date returnDate = jdcReturnDate.getDate();       
           java.sql.Date sqlreturnDate = new java.sql.Date(returnDate.getTime());
           
           BorrowDetailDto detaildto= new BorrowDetailDto(txtBorrowId.getText(),txtBookId.getText(),Integer.parseInt(txtBookQty.getText()),
                  sqlreturnDate,Double.parseDouble(txtFines.getText()));
          ;
                   
          String resp = borrowController.returnBook(detaildto);
          JOptionPane.showMessageDialog(this, resp);
        }catch(Exception e){
            e.printStackTrace();
          JOptionPane.showMessageDialog(this, "Error returning the book");
        }
          
    }
}
