/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.lms.view;

/**
 *
 * @author USER
 */
public class StaffDashboard extends javax.swing.JFrame {

    /**
     * Creates new form StaffDashboard
     */
    public StaffDashboard() {
        super("Staff Dashboard");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnStaffAddB = new javax.swing.JButton();
        btnStaffAddM = new javax.swing.JButton();
        btnStaffIssueB = new javax.swing.JButton();
        btnStaffReturn = new javax.swing.JButton();
        btnStaffAddB1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnStaffAddB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStaffAddB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/lms/view/icons8-glossary-100.png"))); // NOI18N
        btnStaffAddB.setText("Category Info");
        btnStaffAddB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffAddBActionPerformed(evt);
            }
        });

        btnStaffAddM.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStaffAddM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/lms/view/icons8-contacts-100.png"))); // NOI18N
        btnStaffAddM.setText("Add Member");
        btnStaffAddM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffAddMActionPerformed(evt);
            }
        });

        btnStaffIssueB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStaffIssueB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/lms/view/icons8-book-reading-100.png"))); // NOI18N
        btnStaffIssueB.setText("Issue Book");
        btnStaffIssueB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffIssueBActionPerformed(evt);
            }
        });

        btnStaffReturn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStaffReturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/lms/view/icons8-u-turn-100.png"))); // NOI18N
        btnStaffReturn.setText("Return Book");
        btnStaffReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffReturnActionPerformed(evt);
            }
        });

        btnStaffAddB1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStaffAddB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/lms/view/icons8-book-shelf-100.png"))); // NOI18N
        btnStaffAddB1.setText(" Books Info");
        btnStaffAddB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffAddB1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnStaffAddM)
                    .addComponent(btnStaffAddB1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStaffReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStaffIssueB))
                .addGap(114, 114, 114))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(btnStaffAddB, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStaffAddM, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStaffIssueB, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addComponent(btnStaffAddB1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnStaffReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGap(46, 46, 46)
                .addComponent(btnStaffAddB, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStaffAddMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffAddMActionPerformed
        // TODO add your handling code here:
         setVisible(false);
         new MemberView().setVisible(true);
    }//GEN-LAST:event_btnStaffAddMActionPerformed

    private void btnStaffIssueBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffIssueBActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        new BorrowView().setVisible(true);
    }//GEN-LAST:event_btnStaffIssueBActionPerformed

    private void btnStaffAddBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffAddBActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new CategoryView().setVisible(true);
    }//GEN-LAST:event_btnStaffAddBActionPerformed

    private void btnStaffReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffReturnActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        new ReturnView().setVisible(true);
    }//GEN-LAST:event_btnStaffReturnActionPerformed

    private void btnStaffAddB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffAddB1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new BookView().setVisible(true);
    }//GEN-LAST:event_btnStaffAddB1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStaffAddB;
    private javax.swing.JButton btnStaffAddB1;
    private javax.swing.JButton btnStaffAddM;
    private javax.swing.JButton btnStaffIssueB;
    private javax.swing.JButton btnStaffReturn;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
